steps:
- name: 'ubuntu'
  args: ['echo','Hello from step-1']

- name: 'ubuntu'
  args: ['echo', 'Hello from step-2']

- name: 'ubuntu'
  args: ['echo', 'Hello from step-3']

options:
  logging: CLOUD_LOGGING_ONLY