steps:
- name: 'ubuntu'
  args: ['echo','Pipeline Starts']

- name: 'ubuntu'
  args: ['sleep','20s']
  

- name: 'ubuntu'
  args: ['echo','Pipeline Ends']

timeout: 10s

options: 
  logging: CLOUD_LOGGING_ONLY

  