steps: 
- name: "bash"
  script: |
  #!/usr/bin/env bash
  echo "Hello World" > dummy.txt
  echo "Hello World Again" >> dummy.txt
  echo "Opening dummy.txt"
  cat dummy.txt

options: 
  logging: CLOUD_LOGGING_ONLY