steps:
  - name: "ubuntu"
    env: 
      - "NAME=John"
    script: |
      #!/usr/bin/env bash
      echo "Hello $NAME"


  - name: "ubuntu"
    env:
      - "PROJ_ID=$PROJECT_ID"
    script: |
      #!/usr/bin/env bash
      echo "Your project id is: $PROJ_ID"

options:
  logging: CLOUD_LOGGING_ONLY