steps:
- name: "bash"
  script: |
    #!/usr/bin/env bash
    echo "Hello World"

- name: "python"
  script: |
    #!/usr/bin/env python
    print("Hello World from python")


options:
  logging: CLOUD_LOGGING_ONLY