steps:
  - name: "ubuntu"
    script: |
      #!/usr/bin/env bash
      echo "Hello $_NAME"

  - name: "ubuntu"
    script: |
      #!/usr/bin/env bash
      echo "Your project id is: $PROJECT_ID"
    automapSubstitutions: true

substitutions:
  _NAME: "John"

options:
  logging: CLOUD_LOGGING_ONLY